initial commit

diff --git a/.github/workflows/docker-build.yml b/.github/workflows/docker-build.yml
--- a/.github/workflows/docker-build.yml
+++ b/.github/workflows/docker-build.yml
@@ -53,133 +53,134 @@ env:
   TEST_TAG: "digitranslab/kozmoai:test"
 
 jobs:
-  get-version:
-    name: Get Version
-    runs-on: ubuntu-latest
-    outputs:
-      version: ${{ steps.get-version-input.outputs.version || steps.get-version-base.outputs.version || steps.get-version-main.outputs.version }}
-    steps:
-      - name: Verify a main version exists
-        if: ${{ inputs.main_version == '' }}
-        run: |
-          # due to our how we split packages, we need to have a main version to check out.
-          echo "Must specify a main version to check out."
-          exit 1
+#  get-version:
+#    name: Get Version
+#    runs-on: ubuntu-latest
+#    outputs:
+#      version: ${{ steps.get-version-input.outputs.version || steps.get-version-base.outputs.version || steps.get-version-main.outputs.version }}
+#    steps:
+#      - name: Verify a main version exists
+#        if: ${{ inputs.main_version == '' }}
+#        run: |
+#          # due to our how we split packages, we need to have a main version to check out.
+#          echo "Must specify a main version to check out."
+#          exit 1
+#
+#      - name: Check out the code at a specific ref
+#        uses: actions/checkout@v4
+#        with:
+#          ref: ${{ inputs.ref || inputs.main_version || github.ref }}
+#          persist-credentials: true
+#
+#      - name: Get Version to Tag
+#        if: ${{ inputs.main_version != '' }}
+#        id: get-version-input
+#        run: |
+#          # Produces the versions we will use to tag the docker images with.
+#
+#          if [[ "${{ inputs.release_type }}" == "base" && "${{ inputs.base_version }}" == '' ]]; then
+#            echo "Must specify a base version for base release type."
+#            exit 1
+#          fi
+#
+#          if [[ "${{ inputs.release_type }}" == "nightly-base" && "${{ inputs.base_version }}" == '' ]]; then
+#            echo "Must specify a base version for nightly-base release type."
+#            exit 1
+#          fi
+#
+#          if [[ "${{ inputs.release_type }}" == "main" && "${{ inputs.main_version }}" == '' ]]; then
+#            echo "Must specify a main version for main release type."
+#            exit 1
+#          fi
+#
+#          if [[ "${{ inputs.release_type }}" == "main-ep" && "${{ inputs.main_version }}" == '' ]]; then
+#            echo "Must specify a main version for main-ep release type."
+#            exit 1
+#          fi
+#
+#          if [[ "${{ inputs.release_type }}" == "nightly-main" && "${{ inputs.main_version }}" == '' ]]; then
+#            echo "Must specify a main version for nightly-main release type."
+#            exit 1
+#          fi
+#
+#          if [[ "${{ inputs.release_type }}" == "base" || "${{ inputs.release_type }}" == "nightly-base" ]]; then
+#            version=${{ inputs.base_version }}
+#            echo "base version=${{ inputs.base_version }}"
+#            echo version=$version
+#            echo version=$version >> $GITHUB_OUTPUT
+#          elif [[ "${{ inputs.release_type }}" == "main" || "${{ inputs.release_type }}" == "main-ep"  || "${{ inputs.release_type }}" == "nightly-main" ]]; then
+#            version=${{ inputs.main_version }}
+#            echo version=$version
+#            echo version=$version >> $GITHUB_OUTPUT
+#          else
+#            echo "No version or ref specified. Exiting the workflow."
+#            exit 1
+#          fi
+#      - name: Get Version Base
+#        if: ${{ inputs.base_version == '' && (inputs.release_type == 'base' || inputs.release_type == 'nightly-base') }}
+#        id: get-version-base
+#        run: |
+#          version=$(uv tree | grep 'kozmoai-base' | awk '{print $3}' | sed 's/^v//')
+#          if [ -z "$version" ]; then
+#            echo "Failed to extract version from uv tree output"
+#            exit 1
+#          fi
+#          echo version=$version
+#          echo version=$version >> $GITHUB_OUTPUT
+#      - name: Get Version Main
+#        if: ${{ inputs.main_version == '' && (inputs.release_type == 'main' || inputs.release_type == 'main-ep' || inputs.release_type == 'nightly-main') }}
+#        id: get-version-main
+#        run: |
+#          version=$(uv tree | grep 'kozmoai' | grep -v 'kozmoai-base' | awk '{print $2}' | sed 's/^v//')
+#          echo version=$version
+#          echo version=$version >> $GITHUB_OUTPUT
 
-      - name: Check out the code at a specific ref
-        uses: actions/checkout@v4
-        with:
-          ref: ${{ inputs.ref || inputs.main_version || github.ref }}
-          persist-credentials: true
-
-      - name: Get Version to Tag
-        if: ${{ inputs.main_version != '' }}
-        id: get-version-input
-        run: |
-          # Produces the versions we will use to tag the docker images with.
-
-          if [[ "${{ inputs.release_type }}" == "base" && "${{ inputs.base_version }}" == '' ]]; then
-            echo "Must specify a base version for base release type."
-            exit 1
-          fi
-
-          if [[ "${{ inputs.release_type }}" == "nightly-base" && "${{ inputs.base_version }}" == '' ]]; then
-            echo "Must specify a base version for nightly-base release type."
-            exit 1
-          fi
-
-          if [[ "${{ inputs.release_type }}" == "main" && "${{ inputs.main_version }}" == '' ]]; then
-            echo "Must specify a main version for main release type."
-            exit 1
-          fi
-
-          if [[ "${{ inputs.release_type }}" == "main-ep" && "${{ inputs.main_version }}" == '' ]]; then
-            echo "Must specify a main version for main-ep release type."
-            exit 1
-          fi
-
-          if [[ "${{ inputs.release_type }}" == "nightly-main" && "${{ inputs.main_version }}" == '' ]]; then
-            echo "Must specify a main version for nightly-main release type."
-            exit 1
-          fi
-
-          if [[ "${{ inputs.release_type }}" == "base" || "${{ inputs.release_type }}" == "nightly-base" ]]; then
-            version=${{ inputs.base_version }}
-            echo "base version=${{ inputs.base_version }}"
-            echo version=$version
-            echo version=$version >> $GITHUB_OUTPUT
-          elif [[ "${{ inputs.release_type }}" == "main" || "${{ inputs.release_type }}" == "main-ep"  || "${{ inputs.release_type }}" == "nightly-main" ]]; then
-            version=${{ inputs.main_version }}
-            echo version=$version
-            echo version=$version >> $GITHUB_OUTPUT
-          else
-            echo "No version or ref specified. Exiting the workflow."
-            exit 1
-          fi
-      - name: Get Version Base
-        if: ${{ inputs.base_version == '' && (inputs.release_type == 'base' || inputs.release_type == 'nightly-base') }}
-        id: get-version-base
-        run: |
-          version=$(uv tree | grep 'kozmoai-base' | awk '{print $3}' | sed 's/^v//')
-          if [ -z "$version" ]; then
-            echo "Failed to extract version from uv tree output"
-            exit 1
-          fi
-          echo version=$version
-          echo version=$version >> $GITHUB_OUTPUT
-      - name: Get Version Main
-        if: ${{ inputs.main_version == '' && (inputs.release_type == 'main' || inputs.release_type == 'main-ep' || inputs.release_type == 'nightly-main') }}
-        id: get-version-main
-        run: |
-          version=$(uv tree | grep 'kozmoai' | grep -v 'kozmoai-base' | awk '{print $2}' | sed 's/^v//')
-          echo version=$version
-          echo version=$version >> $GITHUB_OUTPUT
-  setup:
-    runs-on: ubuntu-latest
-    needs: get-version
-    outputs:
-      docker_tags: ${{ steps.set-vars.outputs.docker_tags }}
-#      ghcr_tags: ${{ steps.set-vars.outputs.ghcr_tags }}
-      file: ${{ steps.set-vars.outputs.file }}
-    steps:
-      - name: Set Dockerfile and Tags
-        id: set-vars
-        run: |
-          nightly_suffix=''
-          if [[ "${{ inputs.release_type }}" == "nightly-base" || "${{ inputs.release_type }}" == "nightly-main" ]]; then
-            nightly_suffix="-nightly"
-          fi
-
-          if [[ "${{ inputs.release_type }}" == "base" || "${{ inputs.release_type }}" == "nightly-base" ]]; then
-            # KOZMOAI-BASE RELEASE
-            echo "docker_tags=digitranslab/kozmoai${nightly_suffix}:base-${{ needs.get-version.outputs.version }},digitranslab/kozmoai${nightly_suffix}:base-latest" >> $GITHUB_OUTPUT
-            # echo "ghcr_tags=ghcr.io/digitranslab/kozmoai${nightly_suffix}:base-${{ needs.get-version.outputs.version }},ghcr.io/digitranslab/kozmoai${nightly_suffix}:base-latest" >> $GITHUB_OUTPUT
-            echo "file=./docker/build_and_push_base.Dockerfile" >> $GITHUB_OUTPUT
-          else
-            if [[ "${{ inputs.pre_release }}" == "true" ]]; then
-              # KOZMOAI-MAIN PRE-RELEASE
-              echo "docker_tags=digitranslab/kozmoai${nightly_suffix}:${{ needs.get-version.outputs.version }}" >> $GITHUB_OUTPUT
-              # echo "ghcr_tags=ghcr.io/digitranslab/kozmoai${nightly_suffix}:${{ needs.get-version.outputs.version }}" >> $GITHUB_OUTPUT
-              echo "file=./docker/build_and_push.Dockerfile" >> $GITHUB_OUTPUT
-            elif [[ "${{ inputs.release_type }}" == "main-ep" ]]; then
-              # KOZMOAI-MAIN (ENTRYPOINT) RELEASE
-              echo "docker_tags=digitranslab/kozmoai-ep${nightly_suffix}:${{ needs.get-version.outputs.version }},digitranslab/kozmoai-ep${nightly_suffix}:latest" >> $GITHUB_OUTPUT
-              # echo "ghcr_tags=ghcr.io/digitranslab/kozmoai-ep${nightly_suffix}:${{ needs.get-version.outputs.version }},ghcr.io/digitranslab/kozmoai-ep${nightly_suffix}:latest" >> $GITHUB_OUTPUT
-              echo "file=./docker/build_and_push_ep.Dockerfile" >> $GITHUB_OUTPUT
-            elif [[ "${{ inputs.release_type }}" == "main" || "${{ inputs.release_type }}" == "nightly-main" ]]; then
-              # KOZMOAI-MAIN RELEASE
-              echo "docker_tags=digitranslab/kozmoai${nightly_suffix}:${{ needs.get-version.outputs.version }},digitranslab/kozmoai${nightly_suffix}:latest" >> $GITHUB_OUTPUT
-              # echo "ghcr_tags=ghcr.io/digitranslab/kozmoai${nightly_suffix}:${{ needs.get-version.outputs.version }},ghcr.io/digitranslab/kozmoai${nightly_suffix}:latest" >> $GITHUB_OUTPUT
-              echo "file=./docker/build_and_push.Dockerfile" >> $GITHUB_OUTPUT
-            else
-              echo "Invalid release type. Exiting the workflow."
-              exit 1
-            fi
-          fi
+#  setup:
+#    runs-on: ubuntu-latest
+#    needs: get-version
+#    outputs:
+#      docker_tags: ${{ steps.set-vars.outputs.docker_tags }}
+##      ghcr_tags: ${{ steps.set-vars.outputs.ghcr_tags }}
+#      file: ${{ steps.set-vars.outputs.file }}
+#    steps:
+#      - name: Set Dockerfile and Tags
+#        id: set-vars
+#        run: |
+#          nightly_suffix=''
+#          if [[ "${{ inputs.release_type }}" == "nightly-base" || "${{ inputs.release_type }}" == "nightly-main" ]]; then
+#            nightly_suffix="-nightly"
+#          fi
+#
+#          if [[ "${{ inputs.release_type }}" == "base" || "${{ inputs.release_type }}" == "nightly-base" ]]; then
+#            # KOZMOAI-BASE RELEASE
+#            echo "docker_tags=digitranslab/kozmoai${nightly_suffix}:base-${{ needs.get-version.outputs.version }},digitranslab/kozmoai${nightly_suffix}:base-latest" >> $GITHUB_OUTPUT
+#            # echo "ghcr_tags=ghcr.io/digitranslab/kozmoai${nightly_suffix}:base-${{ needs.get-version.outputs.version }},ghcr.io/digitranslab/kozmoai${nightly_suffix}:base-latest" >> $GITHUB_OUTPUT
+#            echo "file=./docker/build_and_push_base.Dockerfile" >> $GITHUB_OUTPUT
+#          else
+#            if [[ "${{ inputs.pre_release }}" == "true" ]]; then
+#              # KOZMOAI-MAIN PRE-RELEASE
+#              echo "docker_tags=digitranslab/kozmoai${nightly_suffix}:${{ needs.get-version.outputs.version }}" >> $GITHUB_OUTPUT
+#              # echo "ghcr_tags=ghcr.io/digitranslab/kozmoai${nightly_suffix}:${{ needs.get-version.outputs.version }}" >> $GITHUB_OUTPUT
+#              echo "file=./docker/build_and_push.Dockerfile" >> $GITHUB_OUTPUT
+#            elif [[ "${{ inputs.release_type }}" == "main-ep" ]]; then
+#              # KOZMOAI-MAIN (ENTRYPOINT) RELEASE
+#              echo "docker_tags=digitranslab/kozmoai-ep${nightly_suffix}:${{ needs.get-version.outputs.version }},digitranslab/kozmoai-ep${nightly_suffix}:latest" >> $GITHUB_OUTPUT
+#              # echo "ghcr_tags=ghcr.io/digitranslab/kozmoai-ep${nightly_suffix}:${{ needs.get-version.outputs.version }},ghcr.io/digitranslab/kozmoai-ep${nightly_suffix}:latest" >> $GITHUB_OUTPUT
+#              echo "file=./docker/build_and_push_ep.Dockerfile" >> $GITHUB_OUTPUT
+#            elif [[ "${{ inputs.release_type }}" == "main" || "${{ inputs.release_type }}" == "nightly-main" ]]; then
+#              # KOZMOAI-MAIN RELEASE
+#              echo "docker_tags=digitranslab/kozmoai${nightly_suffix}:${{ needs.get-version.outputs.version }},digitranslab/kozmoai${nightly_suffix}:latest" >> $GITHUB_OUTPUT
+#              # echo "ghcr_tags=ghcr.io/digitranslab/kozmoai${nightly_suffix}:${{ needs.get-version.outputs.version }},ghcr.io/digitranslab/kozmoai${nightly_suffix}:latest" >> $GITHUB_OUTPUT
+#              echo "file=./docker/build_and_push.Dockerfile" >> $GITHUB_OUTPUT
+#            else
+#              echo "Invalid release type. Exiting the workflow."
+#              exit 1
+#            fi
+#          fi
 
   build:
     runs-on: ubuntu-latest
-    needs: [get-version, setup]
+#    needs: [get-version, setup]
     steps:
       - name: Check out the code at a specific ref
         uses: actions/checkout@v4
@@ -190,11 +191,14 @@ jobs:
         uses: ./.github/actions/setup-uv
       - name: Install the project
         run: |
-          if [[ "${{ inputs.release_type }}" == "base" || "${{ inputs.release_type }}" == "nightly-base" ]]; then
-            uv sync --directory src/backend/base --no-dev --no-sources
-          else
-            uv sync --no-dev --no-sources
-          fi
+          uv sync --no-dev --no-sources
+#      - name: Install the project
+#        run: |
+#          if [[ "${{ inputs.release_type }}" == "base" || "${{ inputs.release_type }}" == "nightly-base" ]]; then
+#            uv sync --directory src/backend/base --no-dev --no-sources
+#          else
+#            uv sync --no-dev --no-sources
+#          fi
 
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
@@ -210,8 +214,10 @@ jobs:
         with:
           context: .
           push: true
-          file: ${{ needs.setup.outputs.file }}
-          tags: ${{ needs.setup.outputs.docker_tags }}
+          file: ./docker/build_and_push.Dockerfile
+          tags: latest
+#          file: ${{ needs.setup.outputs.file }}
+#          tags: ${{ needs.setup.outputs.docker_tags }}
           platforms: linux/amd64,linux/arm64
           cache-from: type=gha
           cache-to: type=gha,mode=max
@@ -239,7 +245,7 @@ jobs:
     runs-on: ubuntu-latest
     permissions:
       packages: write
-    needs: [build, get-version]
+#    needs: [build, get-version]
     strategy:
       matrix:
         component: [docker-backend, docker-frontend]
@@ -247,12 +253,17 @@ jobs:
         include:
           - component: docker-backend
             dockerfile: ./docker/build_and_push_backend.Dockerfile
-            tags: digitranslab/kozmoai-backend:${{ needs.get-version.outputs.version }},digitranslab/kozmoai-backend:latest
-            kozmoai_image: digitranslab/kozmoai:${{ needs.get-version.outputs.version }}
+            tags: digitranslab/kozmoai-backend:latest
+#            tags: digitranslab/kozmoai-backend:${{ needs.get-version.outputs.version }},digitranslab/kozmoai-backend:latest
+            kozmoai_image: digitranslab/kozmoai:latest
+#            kozmoai_image: digitranslab/kozmoai:${{ needs.get-version.outputs.version }}
+
           - component: docker-frontend
             dockerfile: ./docker/frontend/build_and_push_frontend.Dockerfile
-            tags: digitranslab/kozmoai-frontend:${{ needs.get-version.outputs.version }},digitranslab/kozmoai-frontend:latest
-            kozmoai_image: digitranslab/kozmoai:${{ needs.get-version.outputs.version }}
+            tags: digitranslab/kozmoai-frontend:latest
+#            tags: digitranslab/kozmoai-frontend:${{ needs.get-version.outputs.version }},digitranslab/kozmoai-frontend:latest
+            kozmoai_image: digitranslab/kozmoai:latest
+#            kozmoai_image: digitranslab/kozmoai:${{ needs.get-version.outputs.version }}
 #          - component: ghcr-backend
 #            dockerfile: ./docker/build_and_push_backend.Dockerfile
 #            tags: ghcr.io/digitranslab/kozmoai-backend:${{ needs.get-version.outputs.version }},ghcr.io/digitranslab/kozmoai-backend:latest
